### ISSUE TITLE
Representante Legal

### ISSUE THREAD

**Issue by GilbertQ** [transparentegt/portal#60]
En la pagina de Representantes Legales, al seleccionar listar todos seria conveniente tener botones para filtrar por la primera letra del primer apellido.  Por ejemplo, si quiero buscar a alguien cuyo apellido empieza con T, debo llegar hasta la pagina 129 avanzando de cinco en cinco.

**Comment by str** [comment]
La nueva versión ya tiene esta funcionalidad. La podés probar en http://test.transparente.gt/transparente/representante-legal/index 

usuario: test
password: test

No hemos liberado la nueva versión porque el robot bara barrer datos nuevos se traba por datos con problemas.

**Comment by GilbertQ** [comment]
Simón.  Gracias por el update.  Ya vi la funcionalidad de busqueda y funciona muy bien.  Por otra parte, en la misma pagina hay un par de palabras mal escritas.
![trans](https://cloud.githubusercontent.com/assets/5606557/6402348/8221d228-bdcc-11e4-96b2-567c47bb2007.PNG)

**Comment by str** [comment]
¿Podrías abrir otro bug reportando ese error de ortografía?  Gracias :)
